language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer install -n --prefer-dist

script:
  - composer lint
  - composer test
